### ISSUE TITLE
[Feature Request] implement observability framework

### ISSUE THREAD

**Issue by LemonHX** [Limit-IM/limit-server#15]
# 🚀 Feature Request

**Is your feature request related to a problem? Please describe.**
observability is very important

**Describe the solution you'd like**
prometheus and grafana

**Comment by George-Miao** [comment]
Severak places where we can put data points:
- DB access in [`run_sql`](https://github.com/Limit-IM/limit-server/blob/subs/limit-db/src/lib.rs#L57) macro (exec time and db type)
- Auth service in `request_auth`
- Background task

**Comment by George-Miao** [comment]
Merged #19
